export const HOME_BOOKS = [
  {
    id: 'physique-meca',
    title: 'Mécanique du Point',
    subject: 'Physique',
    author: 'P. Diop',
    color: '#1F3A66',
    accent: '#F2C744',
    free: true,
  },
  {
    id: 'maths-analyse',
    title: 'Analyse — Suites & Limites',
    subject: 'Mathématiques',
    author: 'A. Sané',
    color: '#0F5C42',
    accent: '#9DEBA2',
    free: false,
  },
  {
    id: 'fr-dissertation',
    title: 'Dissertation littéraire',
    subject: 'Français',
    author: 'M. Coulibaly',
    color: '#7A2326',
    accent: '#F0CDA0',
    free: false,
  },
  {
    id: 'svt-genetique',
    title: 'Génétique & Évolution',
    subject: 'SVT',
    author: 'F. Ndiaye',
    color: '#2B6F50',
    accent: '#F5C518',
    free: false,
  },
  {
    id: 'philo-conscience',
    title: 'La Conscience',
    subject: 'Philosophie',
    author: 'O. Sow',
    color: '#3D2A60',
    accent: '#E8624C',
    free: false,
  },
  {
    id: 'hg-mondialisation',
    title: 'La Mondialisation',
    subject: 'Histoire-Géo',
    author: 'K. Traoré',
    color: '#8C4A1E',
    accent: '#FFD9A8',
    free: false,
  },
] as const;

export type HomeBook = typeof HOME_BOOKS[number];
